[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace]
members = [
  "pc_client",
  "playdate_client",
  "bouquet_ribbon",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

