[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace]
members = [
  "client_core",
  "client_pc",
  "client_playdate",
  "bouquet_ribbon",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

