[package]
name = "client_core"
version.workspace = true
edition.workspace = true

[dependencies]
bouquet_ribbon = { path = "../bouquet_ribbon" }
rhai = { version = "1.11.0", features = [ "no_std", "no_float", "only_i32" ], default_features = false }

