[package]
name = "bouquet_ribbon"
version.workspace = true
edition.workspace = true

[dependencies]
hashbrown = "0.14"
rhai = { version = "1.15.1", features = [ "no_std", "no_float", "only_i32" ], default_features = false }

